//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoHS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCAMA
    {
        public string CODCAM { get; set; }
        public string ESTCAM { get; set; }
        public string NOMBPAC { get; set; }
        public string NOMBEMF { get; set; }
        public string TIMEIN { get; set; }
        public string TIMEOFF { get; set; }
        public string TIMEACT { get; set; }
    }
}
