//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoHS.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.InterfazHS")]
    public interface InterfazHS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfazHS/GuardarDatos", ReplyAction="http://tempuri.org/InterfazHS/GuardarDatosResponse")]
        void GuardarDatos(string nombre, string tiempo, string efermera, string numcam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfazHS/GuardarDatos", ReplyAction="http://tempuri.org/InterfazHS/GuardarDatosResponse")]
        System.Threading.Tasks.Task GuardarDatosAsync(string nombre, string tiempo, string efermera, string numcam);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InterfazHSChannel : ProyectoHS.ServiceReference1.InterfazHS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfazHSClient : System.ServiceModel.ClientBase<ProyectoHS.ServiceReference1.InterfazHS>, ProyectoHS.ServiceReference1.InterfazHS {
        
        public InterfazHSClient() {
        }
        
        public InterfazHSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfazHSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfazHSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfazHSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GuardarDatos(string nombre, string tiempo, string efermera, string numcam) {
            base.Channel.GuardarDatos(nombre, tiempo, efermera, numcam);
        }
        
        public System.Threading.Tasks.Task GuardarDatosAsync(string nombre, string tiempo, string efermera, string numcam) {
            return base.Channel.GuardarDatosAsync(nombre, tiempo, efermera, numcam);
        }
    }
}
